map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream spidershare_api {
  server api:8000;
}

upstream spidershare_backoffice {
  server backoffice:5173;
}

server {
  listen 80;
  server_name ${API_DOMAIN} ${BACKOFFICE_DOMAIN};

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  server_name ${API_DOMAIN};

  ssl_certificate /etc/letsencrypt/live/${API_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${API_DOMAIN}/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SpiderShareApiSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

  location / {
    proxy_pass http://spidershare_api;
    proxy_http_version 1.1;
    proxy_read_timeout 900s;
    proxy_send_timeout 900s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Request-ID $request_id;
  }
}

server {
  listen 443 ssl http2;
  server_name ${BACKOFFICE_DOMAIN};

  ssl_certificate /etc/letsencrypt/live/${BACKOFFICE_DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${BACKOFFICE_DOMAIN}/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SpiderShareBackofficeSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

  location /api/ {
    proxy_pass http://spidershare_api/;
    proxy_http_version 1.1;
    proxy_read_timeout 900s;
    proxy_send_timeout 900s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Request-ID $request_id;
  }

  location / {
    proxy_pass http://spidershare_backoffice;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Request-ID $request_id;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
